AUCs
****
EXAMINATION AND ANALYSIS OF THE FIRE SCENE IS NECESSARY TO DETERMINE THE CAUSE AND ORIGIN OF THE FIRE. UNTIL THIS DETERMINATION IS MADE THE ENTIRE FIRE SCENE SHOULD BE CONSIDERED EVIDENCE. WHICH CHOICE BELOW CONTAINS CORRECT INFORMATION REGARDING POSSIBLE CRIME SCENE OPERATIONS?
The use of gasoline powered equipment should be immediately prohibited.
--  The preservation of the fire scene should begin with the first due companies. Units should avoid unnecessary disturbance of the scene during operations, particularly while overhauling.
All DOA's, unless EMS-related, should be treated as a potential crime victim.
The fire scene becomes a crime scene if the Incident Commander declares the fire to be incendiary (intentionally set).
A) THE USE OF GASOLINE POWERED EQUIPMENT SHOULD BE CAREFULLY MONITORED TO GUARD AGAINST FUEL SPILLAGE.
C) ALL DOA'S WHETHER FIRE RELATED OR EMS GENERATED SHOULD BE TREATED AS A POTENTIAL CRIME VICTIM.
D) THE FIRE SCENE BECOMES A CRIME SCENE IF FIRE MARSHALS DECLARE THE FIRE TO BE INCENDIARY (INTENTIONALLY SET).
AUC 317 2,3

MEMBERS OPERATING AT THE SCENE OF A FIRE SHOULD REALIZE THERE ARE ___ LIABILITIES INVOLVED IN DISCARDING POTENTIAL EVIDENCE (OUT WINDOWS, ETC.) DURING THE COURSE OF OPERATIONS OR OVERHAULING.
Many
-- No
Definite
Always
HOWEVER, AS PROFESSIONALS, MEMBERS SHOULD STRIVE TO ASSIST MARSHALS IN THEIR INVESTIGATION BY RELAYING DETAILS TO FACILITATE RECONSTRUCTION OF THE SCENE AND THE PROPER PLACEMENT OF POTENTIAL EVIDENCE.
AUC 317 7.6

IN CIRCUMSTANCES WHERE MEMBERS OF THE FIRE DEPARTMENT DISCOVER DRUGS OR WEAPONS DURING LEGITIMATE EMERGENCY SEARCHES THEY WOULD BE ACTING OUTSIDE OF THE PERMITTED LIMITED SCOPE OF WARRANTLESS SEARCH AND SEIZURE IN FIRE SITUATIONS, IF THEY SEIZED THE EVIDENCE. THEREFORE MEMBERS OF THE FORCE SHOULD REFER SUCH KNOWLEDGE OF ILLEGAL SUBSTANCES TO ________, WHO CAN DETERMINE THE NECESSITY FOR A WARRANT, OR ACT WITHIN SOME OTHER EXCEPTION TO THE WARRANTLESS SEARCH.
The police
The Supervising Fire Marshal
The Incident Commander
The IG
IN CIRCUMSTANCES WHERE MEMBERS OF THE FIRE DEPARTMENT DISCOVER DRUGS OR WEAPONS DURING LEGITIMATE EMERGENCY SEARCHES THEY WOULD BE ACTING OUTSIDE OF THE PERMITTED LIMITED SCOPE OF WARRANTLESS SEARCH AND SEIZURE IN FIRE SITUATIONS, IF THEY SEIZED THE EVIDENCE. THEREFORE MEMBERS OF THE FORCE SHOULD REFER SUCH KNOWLEDGE OF ILLEGAL SUBSTANCES TO THE POLICE, WHO CAN DETERMINE THE NECESSITY FOR A WARRANT, OR ACT WITHIN SOME OTHER EXCEPTION TO THE WARRANTLESS SEARCH.
AUC 317 Add 1
