COMMUNICATIONS MANUAL
*********************
YOU ARE CALLED IN TO INVESTIGATE A SUSPICIOUS FIRE IN A COMPACTOR SHAFT. WHAT WOULD BE THE CORRECT CODE TRANSMITTED BY THE INCIDENT COMMANDER FOR A COMPACTOR FIRE, WHERE FIRE HAS NOT EXTENDED FROM THE COMPACTOR OR SHAFT?
-- 10-27
10-31
10-28
10-32
COMM 8.5

WHAT WOULD BE THE MOST CORRECT CODE FOR AN INCIDENT COMMANDER TO TRANSMIT WHEN \"A SPRINKLER HAS BEEN ACTIVATED BY A HEAT SOURCE NOT ASSOCIATED WITH AN ACCIDENTAL FIRE?\"
10-34 code 1
10-34 code 2
-- 10-34 code 3
10-34 code 4
A) DEFECTIVE SPRINKLER DEVICE OR SYSTEM (DEFECTIVE ALARM VALVE, BROKEN PIPE, ETC.)
B) UNWARRANTED SPRINKLER ALARM- NOT DEFECTIVE (SURGE IN PRESSURE, PEOPLE WORKING ON THE SYSTEM, ETC.)
D) CODE DOES NOT EXIST
COMM 8.5

FIRE MARSHAL PHILLIPS ARRIVES AT THE SCENE OF A SHED FIRE IN THE REAR YARD OF A PRIVATE DWELLING. THE SHED IS UNOCCUPIED AND STORES YARD EQUIPMENT. THE IC CORRECTLY TRANSMITTED
10-41 code 1
10-41 code 2
10-41 code 3
-- 10-41 code 4
COMMUNICATIONS CH 8 PAGE 12

A FIRE BROKE OUT IN A PD AT 11AM AND THE OCCUPANT WAS NOT AT HOME AT THE TIME OF THE FIRE. FIRE MARSHAL SMITH RESPONDED AND ASKED THE IC WHICH CODE WAS TRANSMITTED. MARSHAL SMITH CORRECTED THE IC AND TRANSMITTED THE FOLLOWING CODE
10-41 code 1
-- 10-41 code 2
10-41 code 3
10-41 code 4
COMMUNICATIONS Ch 8 Pg 12
A STRUCTURE (COMMERCIAL, RESIDENTIAL, PUBLIC), NORMALLY OCCUPIED WHICH IS UNOCCUPIED AT THE TIME OF THE FIRE

WHAT CODE SHOULD BE TRANSMITTED WHEN A FIRE MARSHAL INVESTIGATION IS REQUIRED FOR A FIRE IN AN UNOCCUPIED AUTOMOBILE, WITHOUT PLATES?
10-41 code 1
10-41 code 2
-- 10-41 code 3
10-41 code 4
C) A VEHICLE, (CAR, BUS OR TRAIN) WITH OR WITHOUT PLATES, WHICH IS UNOCCUPIED AT THE TIME OF THE FIRE.
COMM 8.5

A FRUSTRATED CHIEF CALLS YOUR OFFICE ASKING YOU TO ASSIST HIM IN DEALING WITH A HIGH-RISE BUILDING WHERE THERE HAVE BEEN NUMEROUS ALARM ACTIVATIONS AS A RESULT OF PERSONS SMOKING CIGARETTES IN UNAUTHORIZED AREAS. REVIEWING BUILDING RECORDS, YOU WOULD BE CORRECT TO FIND A LARGE NUMBER OF ____ TRANSMITTED FOR THIS LOCATION.
10-35 no codes
10-35 code 2s
10-35 code 3s
-- 10-35 code 4s
A) UNWARRANTED ALARM. ALARM SYSTEM ACTIVATION CAUSED BY A DEFECTIVE CONDITION.
B) UNNECESSARY ALARM CAUSED BY CONSTRUCTION ACTIVITIES.
C) UNNECESSARY ALARM CAUSED BY ORDINARY HOUSEHOLD ACTIVITIES (TOAST, STEAM, AEROSOL SPRAY).
COMM 8.5

YOU ARE SPECIAL CALLED TO PROVIDE SECURITY FOR UNITS AT A 10-39. YOU WERE CORRECT TO KNOW UNITS WOULD BE TAKING WHICH ACTION UPON YOUR ARRIVAL?
-- Standing by
Investigating a Carbon Monoxide Incident
Assisting a civilian
Providing medical care (non fire-related)
B) 10-38
C) 10-31
D) 10-37
COMM 8.5

EVERY FIRE MARSHAL SHOULD KNOW HOW TO COMMUNICATE OVER THE DEPARTMENT RADIO WITH THE "MIXER OFF." WHICH CHOICE BELOW CONTAINS INCORRECT INFORMATION REGARDING THIS IMPORTANT COMMUNICATION METHOD?
"Mixer off" messages can only be transmitted by mobile units.
Since information transmitted from the scene of an incident may be critical to all concerned, the Radio Dispatcher shall not switch the "Mixer off", unless specifically requested to do so by the unit transmitting the message.
If in the dispatcher's experience, he or she believes the mixer should be off for confidentiality purposes, the dispatcher will automatically turn the mixer off in all cases.
The Radio Dispatcher shall switch the "Mixer off" if the names and/or units of injured members are being received, and/or information associated with the transmission of a 10-41 is being received.
C) IF IN THE DISPATCHER'S EXPERIENCE, HE OR SHE BELIEVES THE MIXER SHOULD BE OFF FOR CONFIDENTIALITY PURPOSES, THE UNIT TRANSMITTING THE MESSAGE SHALL BE ASKED IF THE MIXER SHOULD BE SWITCHED OFF.
COMM 8.2.9

WHILE RESPONDING TO A SUSPICIOUS FIRE IN A COMMERCIAL BUILDING, THE DISPATCHER NOTIFIES YOU THAT THE THE SUPERVISING FIRE MARSHAL WANTS YOU TO \"10-2.\" YOU WOULD BE MOST CORRECT TO KNOW THAT THIS MEANS YOU SHOULD?
Call your quarters
-- Return to quarters
Call the dispatcher by telephone
Give your location to the dispatcher
COMM 8.5

WHILE INVESTIGATING A STRING OF INCIDENTS WHERE A HOMELESS PERSON IS SUSPECTED OF LIGHTING TRASH FIRES UNDERNEATH THE SEATS OF SUBWAY CARS IN THE BRONX, YOU WOULD BE CORRECT TO LISTEN FOR THE TRANSMISSION OF WHICH SIGNAL IN THIS BOROUGH?
10-28 code 1
-- 10-28 code 2
10-28 code 3
10-31
A CODE 2 IS FOR A SUBWAY FIRE THAT IS "NON-STRUCTURAL" E.G. TRAIN FIRE, RUBBISH ON THE TRACKS, ETC.) OF COURSE, THIS SIGNAL WOULD BE IN ADDITION TO THE APPROPRIATE 10-41 CODE IN THIS SCENARIO.
COMM 8.5

YOU ARE RESPONDING TO A LARGE, SUSPICIOUS RUBBISH FIRE LOCATED OUTSIDE A FOREIGN EMBASSY. THE UNIT THAT EXTINGUISHED THE BLAZE TRANSMITTED A 10-99. YOU WOULD BE CORRECT TO KNOW THAT THIS UNIT WILL BE ON SCENE, OPERATING FOR AT LEAST?
15 minutes
-- 30 minutes
20 minutes
60 minutes
COMM 8.5

WHILE INTERVIEWING WITNESSES OF A LARGE FIRE WHERE TWO 10-45 CODE 3\'S WERE TRANSMITTED YOU WERE CORRECT TO KNOW THAT THESE TWO CIVILIANS SUFFERED WHAT TYPE OF INJURIES?
Life-threatening
-- Non-life threatening
Non-serious
Minor
COMM 8.5

YOU ARE SPECIAL CALLED TO PROVIDE SECURITY AT A LARGE SCALE "MAJOR EMERGENCY RESPONSE" WHERE "ENHANCED TECHNICAL RESCUE RESOURCES" ARE REQUIRED. YOU WOULD BE CORRECT TO KNOW THAT YOU WOULD BE OPERATING AT AN EVENT DEFINED BY WHICH CODE?
10-60 no code
10-60 code 1
-- 10-60 code 2
10-60 code 3
A) Major Emergency Response
B) Major Emergency Response - Enhanced Technical Rescue Resources Required
C) Major Emergency Response - Enhanced Technical Rescue Resources Required - Large Scale
COMM 8.5

THE INCIDENT COMMANDER MUST NOTIFY THE DISPATCHER BY RADIO THAT THE FIRE IS SUSPICIOUS PRIOR TO LEAVING THE SCENE. IF, AFTER LEAVING THE SCENE, INFORMATION BECOMES AVAILABLE WHICH INDICATES THAT THE FIRE IS SUSPICIOUS, THE INCIDENT COMMANDER SHALL IMMEDIATELY NOTIFY ________ BY TELEPHONE, THAT THE FIRE HAS BEEN DECLARED SUSPICIOUS.
The Dispatcher only
The Bureau of Fire Investigation only
-- The Dispatcher and the Bureau of Fire Investigation
Fire Department Operations Center (FDOC)
COMM 8.5

DURING YOUR INVESTIGATION OF A SUSPICIOUS VEHICLE FIRE, A CIVILIAN PASSING BY FALLS AND BREAKS HER LEG. YOU WOULD BE CORRECT TO TRANSMIT WHICH CODE?
10-42
10-43
10-44
10-54
10-44: A REQUEST FOR AN AMBULANCE RESPONSE FROM THE EMS COMMAND. SPECIFY THE REASON AND TYPE (WHEN POSSIBLE).
COMM 8.5

