FIREFIGHTING PROCEDURES
***********************
ALL VACANT BUILDINGS MUST BE IDENTIFIED AND MARKED WITH THE DESIGNATED SYMBOL. WHICH CHOICE BELOW DOES NOT CONTAIN CORRECT INFORMATION REGARDING THIS MARKING?
Marking should be in lime yellow, reflective type paint.
The marking should be a SQUARE, approximately 18" x 18".
LINES are to be made 3" wide
Primary markings shall be made alongside the front entrance. If deemed advantageous, additional markings shall be made at other places (fire escape, roof bulkhead, etc.).
C) LINES TO BE 2" WIDE
FFP VACANTS 1.3.2, 1.3.3

_____ VAPORS, IMMEDIATELY UPON IGNITION, BURN WITH LIGHTNING RAPIDITY WITH HIGH HEAT PRODUCTION. EXPOSED COMBUSTIBLE MATERIAL IN THE FLASH AREA WILL BE IGNITED.
Diesel
Gasoline
Methanol
LPG
FFP VACANTS 1.5.2 C

MOST FIRES ORIGINATE ____________ IN TAXPAYERS, WHERE UTILITIES, STORAGE, AND SERVICES ARE LOCATED. THIS IS THE AREA FROM WHICH THE FIRE USUALLY EXTENDS TO THE COCKLOFT.
in the rear of the first floor
in the front of the first floor
in the rear of the cellar
in the front of the cellar
FFP TXPYRS 5.3.3 C



A SUPERVISING FIRE MARSHAL QUESTIONS YOU ABOUT FIRE SPREAD IN A TAXPAYER CONSTRUCTED UNDER THE 1968 BUILDING CODE. YOU WERE CORRECT TO TELL HER THAT THE PERMITTED AREA OF A TAXPAYER STRUCTURE ACCORDING TO THIS CODE IS _____ SQUARE FEET IF UNSPRINKLERED AND NO LIMIT TO THE AREA IF THE BUILDING IS SPRINKLERED.
24,000
12,000
10,000
-- 7,500
FFP TXPYR APPX A 2.1
