FIREFIGHTING PROCEDURES
***********************
ALL VACANT BUILDINGS MUST BE IDENTIFIED AND MARKED WITH THE DESIGNATED SYMBOL. WHICH CHOICE BELOW DOES NOT CONTAIN CORRECT INFORMATION REGARDING THIS MARKING?
Marking should be in lime yellow, reflective type paint.
The marking should be a SQUARE, approximately 18" x 18".
-- LINES are to be made 3" wide
Primary markings shall be made alongside the front entrance. If deemed advantageous, additional markings shall be made at other places (fire escape, roof bulkhead, etc.).
C) LINES TO BE 2" WIDE
FFP VACANTS 1.3.2, 1.3.3

FIRES IN VAPORS OF _____ FUEL OIL DEVELOP SLOWLY AT THE START, BUT PROGRESS RAPIDLY AS VAPOR PRODUCTION INTENSIFIES.
Gasoline
-- Diesel
Methanol
Natural Gas
FFP VACANTS 1.5.2 A

FOR ______ FIRES, HEAT DEVELOPED WILL BE FOR A LONGER DURATION THAN THAT INVOLVING GASOLINE, IGNITING MORE OF THE COMBUSTIBLE MATERIALS IN THE AREA, AND PRODUCING A FIRE OF RAPID SPREAD AND GREATER MAGNITUDE.
LPG
Compressed Gas
-- Diesel
Methanol
FFP VACANTS 1.5.2 A

_____ VAPORS, IMMEDIATELY UPON IGNITION, BURN WITH LIGHTNING RAPIDITY WITH HIGH HEAT PRODUCTION. EXPOSED COMBUSTIBLE MATERIAL IN THE FLASH AREA WILL BE IGNITED.
Diesel
-- Gasoline
Methanol
LPG
FFP VACANTS 1.5.2 C

FIRES IN VACANT BUILDINGS WILL NORMALLY HAVE A RAPID SPREAD DUE TO?
auto exposure
combustible furnishings
interconnected balconies
-- the many exterior and interior openings
D) I.E., WINDOWS REMOVED, HOLES IN FLOORS, ROOFS AND WALLS. DRAFTS OF AIR CREATE A READY SUPPLY OF OXYGEN TO THE FIRE
FFP VACANTS 2.1.1 G

ACCORDING TO FFP TAXPAYERS, _______ ARE PARTICULARLY VULNERABLE TO BACKDRAFTS ALTHOUGH THEY CAN OCCUR IN ANY PART OF A STRUCTURE.
-- cellar and storage areas
1st and 2nd floor areas
Attic and top floor areas
garage and storage areas
FFP TXPYR 4.1.4 D

THERE ARE THREE BASIC FACTORS NECESSARY FOR ORDINARY COMBUSTION AS WELL AS A BACKDRAFT. WHICH CHOICE BELOW IS NOT ONE OF THESE FACTORS?
Combustibles
Oxygen
Heat
-- Flammables
FFP TXPYR 4.4.1

TO ASSESS FIRE CONDITIONS UPON THE ARRIVAL OF FIRST DUE UNITS AT A TAXPAYER FIRE, YOU INTERVIEW MEMBERS WHO DESCRIBE THE COLOR OF SMOKE THEY INITIALLY OBSERVED BEFORE ENTRY. YOU KNOW ALL OF THE FOLLOWING DESCRIBE SMOKE THAT MAY BE INDICATIVE OF A BACKDRAFT EXCEPT IN WHICH CHOICE?
Dirty brown
Yellow brown
Gray yellow
-- Yellow green
D) Dense black
FFP TXPYR 4.4.1 B3

SOME OF THE FACTORS THAT INFLUENCE THE SEVERITY OF A BACKDRAFT ARE INCLUDED BELOW EXCEPT IN WHICH CHOICE?
type of gases, their temperature, pressure and make up
size and location of the areas involved
type and size of openings made by the Fire Department and proximity of openings in relation to the fire
-- amount of turbulence outside the building caused by the direction and velocity of the wind and hose streams directed against the exterior of the building
D) AMOUNT OF TURBULENCE IN THE BUILDING CAUSED BY THE DIRECTION AND VELOCITY OF THE WIND AND HOSE STREAMS DIRECTED IN THE BUILDING
ACRONYM: P GOAT: PROXIMITY OF OPENINGS IN RELATION TO THE FIRE, GAS TYPE, TEMP, PRESS & MAKEUP, OPENINGS MADE BY THE FD, AREA SIZE & LOCATION INVOLVED, TURBULENCE CAUSED BY WIND & HOSE STREAMS
FFP TXPYR 4.4.1 C

A ROOM OR FIRE AREA REQUIRES ONLY ___ PERCENT OF ITS SPACE TO CONTAIN AN EXPLOSIVE MIXTURE FOR THE ENTIRE AREA TO POSSIBLY EXPLODE.
10
-- 25
50
75
THE ENTIRE AREA COULD EXPLODE WHEN FIREFIGHTERS ENTER TO SEARCH AND ALLOW FRESH AIR TO ENTER WITH THEM
FFP TXPYR 4.4.1 F

MOST FIRES ORIGINATE ____________ IN TAXPAYERS, WHERE UTILITIES, STORAGE, AND SERVICES ARE LOCATED. THIS IS THE AREA FROM WHICH THE FIRE USUALLY EXTENDS TO THE COCKLOFT.
-- in the rear of the first floor
in the front of the first floor
in the rear of the cellar
in the front of the cellar
FFP TXPYRS 5.3.3 C

A FIRE MARSHAL WOULD KNOW ALL OF THE FOLLOWING TO BE CORRECT REGARDING TAXPAYER ARSON FIRES EXCEPT IN WHICH CHOICE?
-- In recent years the number of arson related fires have decreased but must still be considered a possible factor.
The means and methods of the arsonist are many. They range from the very simple to the highly sophisticated.
Members must be aware of the possibility of the presence of combustible and flammable liquids which may be used to start and accelerate fires.
Combustible or flammable liquids may be spilled over the floor or contents of a structure or occupancy, accelerating the fire. Flammable vapors, upon reaching a source of ignition, may flash back and fire may involve the entire occupancy or structure.
A) IN RECENT YEARS THE NUMBER OF ARSON RELATED FIRES HAS INCREASED SIGNIFICANTLY AND MUST BE CONSIDERED A POSSIBLE FACTOR.
FFP TXPYR 4.6.1-4.6.4

FIRE MAY SPREAD VERTICALLY IN TAXPAYERS VIA ALL OF THE FOLLOWING EXCEPT?
concealed spaces between furred plaster and brick walls.
open stairs or trap-doors
-- conduction -mushrooming at upper levels
shafts- light and ventilation shafts from interior bathrooms and offices.
C) CONVECTION -MUSHROOMING AT UPPER LEVEL
FFP TXPYR 4.8.2

HEN A 10-41 IS TRANSMITTED FOR A TAXPAYER-TYPE BUILDING THAT HAS A FIRE COMMAND STATION, THE INCOMING FIRE MARSHAL CAN FIND THE INCIDENT COMMAND POST AT WHAT LOCATION?
Outside, in proximity to the front of the building
In the lobby, in proximity to the Elevator Control Panel
-- At the Fire Command Station
At the Lobby Security Desk
FFP TXPYR 5.8.2

AN EXPERIENCED FIRE MARSHAL WOULD BE CORRECT IN HER STATEMENT THAT IN TAXPAYERS, \"WHEN ROOF VENTILATION IS EFFECTED AND THERE IS A DELAY IN PLACING WATER ON THE FIRE IT INTENSIFIES AND INVARIABLY INVOLVES OTHER STORES, MAINLY VIA THE ______\"
cellar beams
partition walls
roof covering
-- cockloft
FFP TXPYR 6.2.3

A SUPERVISING FIRE MARSHAL QUESTIONS YOU ABOUT FIRE SPREAD IN A TAXPAYER CONSTRUCTED UNDER THE 1968 BUILDING CODE. YOU WERE CORRECT TO TELL HER THAT THE PERMITTED AREA OF A TAXPAYER STRUCTURE ACCORDING TO THIS CODE IS _____ SQUARE FEET IF UNSPRINKLERED AND NO LIMIT TO THE AREA IF THE BUILDING IS SPRINKLERED.
24,000
12,000
10,000
-- 7,500
FFP TXPYR APPX A 2.1

A KNOWLEDGEABLE FIRE MARSHAL SHOULD KNOW THAT ACCORDING TO THE 1968 BUILDING CODE, TAXPAYER TYPE OCCUPANCY BUILDINGS HAVE A FIRE INDEX RATING OF ____.
1
-- 2
3
4
FFP TXPYR APPX A 2.9
