REGULATIONS
***********
MEMBERS SHALL BE REQUIRED TO DEMONSTRATE A MINIMUM LEVEL OF PROFICIENCY WITH FIREARMS HOW OFTEN?
Daily
Yearly
-- As often as directed
Semi-annually
REGS 8.5.1

IN ORDER TO SAFEGUARD PRIVATE PROPERTY WHILE OPERATING, WHEN FDNY MEMBERS FIND ARTICLES OF VALUE, SUCH ARTICLES SHALL BE TURNED OVER TO THEIR IMMEDIATE SUPERVISORY OFFICER, WHO IN TURN SHALL DELIVER THEM TO THE OFFICER IN COMMAND. AN EXPERIENCED FIRE MARSHAL WOULD KNOW THAT THESE ARTICLES MAY BE TURNED OVER TO ALL OF THE FOLLOWING EXCEPT?
Owner, upon proper identification
Police, if owner is not available
An authorized representative of the owner
-- The borough commander if no owner, police officer or authorized representative is on scene
IN ALL CASES A RECEIPT SHALL BE OBTAINED.
REGS 11.3.15 A

FIRE MARSHAL JONES WAS CORRECT IN HIS ASSERTION THAT IF A FIRE OCCURS IN A VEHICLE, OTHER THAN AN ADV OR ONE FOR WHICH A 10-41 CODE 3 HAS BEEN TRANSMITTED, THE INCIDENT COMMANDER SHALL ATTEMPT TO NOTIFY THE OWNER. IF THIS IS NOT POSSIBLE, THE DISPATCHER SHALL BE REQUESTED TO INFORM THE POLICE COMMUNICATIONS BUREAU OF ALL OF THE FOLLOWING EXCEPT?
Make
Model
-- Vehicle registration
Location
C) LICENSE
ACRONYM: MMLL
REGS 11.3.15 D

DURING FIRE OPERATIONS ALL MEMBERS SHALL BE ALERT TO THE POSSIBILITY OF THE CRIME OF ARSON. IN THE EVENT CONDITIONS INDICATE THIS POSSIBILITY, THE INCIDENT COMMANDER SHALL PROMPTLY NOTIFY THE FIRE MARSHAL. WHICH CHOICE BELOW CONTAINS INCORRECT INFORMATION REGARDING MEMBER ACTIONS FROM THIS POINT ON?
Unauthorized persons shall be prohibited from entering the premises or motor vehicle
Actions of members authorized to enter shall be carefully noted
Members shall refrain from discussion of the fire and prevent the disturbance of any essential evidence
-- If necessary, the incident commander shall detail one or more units to remain at the location with the information until the arrival of a fire marshal
IF NECESSARY, THE INCIDENT COMMANDER SHALL DETAIL ONE OR MORE MEMBERS TO REMAIN AT THE LOCATION WITH THE INFORMATION UNTIL THE ARRIVAL OF A FIRE MARSHAL
REGS 11.3.31


HEN UNITS ARE STILL ON THE SCENE OF A FIRE OR EMERGENCY WHICH HAS BEEN UNDER CONTROL FOR MORE THAN __ HOURS, THE INCIDENT WILL BE REFERRED TO AS \"CONTINUING OPERATIONS AT BOX...BORO OF...\" IN ALL RADIO COMMUNICATIONS REFERRING TO THE INCIDENT, OR THE MOVEMENT OF UNITS TO AND FROM THE INCIDENT.
12
-- 8
24
10
REGS 11.4.13


MEMBERS SHALL NOT SELL OR DISTRIBUTE TICKETS, NOR SHALL THEY SELL OR SOLICIT ADVERTISEMENTS FOR EVENTS OF ANY KIND WITHOUT THE PRIOR WRITTEN APPROVAL OF THE ______. SUCH EVENTS INCLUDE, BUT ARE NOT LIMITED TO, UNIT ANNIVERSARIES, SPORTING EVENTS, MEMORIAL RUNS, TOURNAMENTS AND THE LIKE.
-- Fire Commissioner
Chief of Department
Chief Fire Marshal
BITS
APPROVAL WILL NOT BE GRANTED UNLESS IT IS SPECIFICALLY STIPULATED THAT TICKETS AND/OR ADVERTISEMENTS WILL BE SOLD ONLY TO MEMBERS AND THEIR FAMILIES.
REGS 25.2.1

NO MEMBER SHALL MAKE, POSSESS, OR PRESENT A FACSIMILE OF ANY OFFICIAL BADGE OR IDENTIFICATION CARD. MEMBERS SHALL NOT USE OFFICIAL DEPARTMENT BADGES UNDER ANY CIRCUMSTANCES TO ELICIT CONSIDERATION OF A PERSONAL NATURE OR CIRCUMVENT REGULATIONS OR LAWS. FACSIMILE OF BADGES MAY ONLY BE POSSESSED BY MEMBERS WITH THE APPROVAL OF THE _____ WHEN THE BADGE IS PART OF PERMANENT PLAQUE OR TROPHY.
-- Fire Commissioner
Chief of Department
Chief of Operations
Division Commander
REGS 25.2.9


WHEN IT IS REPORTED THAT A CRIMINAL OFFENSE HAS BEEN COMMITTED BY A MEMBER, THE OFFICER ON DUTY SHALL IMMEDIATELY NOTIFY _________.
the supervising Fire Marshal
-- the deputy and battalion chiefs on duty
the battalion chief on duty only
the deputy chief on duty only
THE DEPUTY CHIEF SHALL TELEPHONE PARTICULARS TO THE NOTIFICATION DESK AND THE OFFICE OF THE INSPECTOR GENERAL
REGS 25.4.5

A MEMBER STUDYING FOR THE FIRE MARSHAL EXAM WAS CORRECT WHEN HE EXPLAINED TO ANOTHER MEMBER THAT CHARGES MUST BE PREPARED AND FORWARDED WITH ENDORSEMENTS WITHIN ___ DAYS AFTER OCCURRENCE, UNLESS DELAYED DUE TO UNUSUAL CIRCUMSTANCES.
30
-- 10
5
14
REGS 26.1.3

CHARGES MUST BE FORWARDED TO ______, WHEN WARRANTED.
-- BITS
IG
Chief Fire Marshal
Chief of Operations
CHARGES ARE NOT TO BE SERVED ON THE RESPONDENT UNTIL THEY ARE APPROVED BY THE BUREAU OF INVESTIGATION AND TRIALS (BITS,) WHICH MAY DIRECT THAT FURTHER INVESTIGATION BE CONDUCTED OR FURTHER DOCUMENTATION PROVIDED.
REGS 26.1.3

FDNY MEMBERS SHOULD KNOW THAT WHEN "CHARGES" ARE WARRANTED, THE TRIAL NOTICE MUST BE SERVED ON THE RESPONDENT AT LEAST ___ DAYS BEFORE TIME SET FOR TRIAL UNLESS THE RESPONDENT WAIVES SUCH NOTICE OR APPLIES, OR HAS APPLIED FOR, SERVICE RETIREMENT.
30
-- 10
3
5
REGS 26.5.1
